---
name: converted jenkins pipeline
'on':
- event: :schedule
  cron: "* * * 30 *"
- event: :push
  branches:
  - main
  - release/*
- event: :pull_request
env:
- SHELL: "/bin/bash"
  RUBY-VERSION: 2.7.1
jobs:
- name: build
  runs-on: ubuntu-latest
  steps:
  - name: run command
    run: echo foo
  - name: nitpicker
    uses: ethanis/nitpicker@v1
    with:
    - nitpicks: ".github/nitpicks.yml"
      token: "${{ secrets.GITHUB_TOKEN }}"
  - name: unknown builder
    uses: hudson.plugins.copyartifact.CopyArtifact
    unknown: true
- name: release
  runs-on: ubuntu-latest
  needs:
  - build
  env:
  - SERVER: production
  steps:
  - name: run command
    run: echo $SERVER
