name: build-playground/unit-tests/Github_Release_Test
on:
  workflow_dispatch:
env:
  adminUserName: Begona
jobs:
  Stage-1-job-1:
    runs-on: windows-latest
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: true
    env:
      ALT: one1, one2
      TARGETS: suite1,suite2
      favorite_ice_cream: Mango
      favorite_movie: Pride and Prejudice
    if: # roll back deployment stage triggers are not supported
        github.event_type != 'pull_request'
    timeout-minutes: 99
    strategy:
    steps:
    # If `begonaguereca/artifacts` is the same as the current repository, the `token` property can be removed.
    - uses: actions/checkout@v2
      with:
        repository: begonaguereca/artifacts
        ref: main
        fetch-depth: '1'
        path: _begonaguereca_artifacts
        submodules: 'true'
        token: "${{ secrets.CHECKOUT_TOKEN }}"
    - uses: Azure/login@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
    - uses: azure/CLI@v1
      with:
        inlineScript: az storage blob download --name storage_this --file test
    # If `build-playground/build-playground` is the same as the current repository, the `token` property can be removed.
    - uses: actions/checkout@v2
      with:
        repository: build-playground/build-playground
        path: _build-playground_tfvc
        token: "${{ secrets.CHECKOUT_TOKEN }}"
    - uses: dsaltares/fetch-gh-release-asset@0.06
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        repo: begonaguereca/American_Flag
        version: '1.2'
    - name: Authenticate GitHub Packages
      uses: whelk-io/maven-settings-xml-action@v20
      repositories: '[{"id":"1","url":"https://maven.pkg.github.com/${{ env.PACKAGES_OWNER }}/${{ env.PACKAGES_REPOSITORY }}"}]'
      servers: '[{"id":"1","username":"${{ env.PACKAGES_USERNAME }}","password":"${{ secrets.PACKAGES_TOKEN }}"}]'
    # # Ensure the following is included in your pom.xml file
    # <dependencies>
    #   <dependency>
    #     <groupId>1</groupId>
    #     <artifactId>1</artifactId>
    #     <version>latest</version>
    #   </dependency>
    # </dependencies>
    - name: Install Maven packages
      run: mvn install -s ~/.m2/settings.xml
    - name: Authenticate GitHub Packages
      run: echo '//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}' > ~/.npmrc
    - name: Install NPM packages
      run: npm install @${{ env.PACKAGES_OWNER }}/1@latest --registry=https://npm.pkg.github.com/${{ env.PACKAGES_OWNER }}
#     # GitHub Packages does not support downloading `python` packages
#     # GitHub Packages does not support downloading `universal` packages
    # If `valet-testing/dast` is the same as the current repository, the `token` property can be removed.
    - uses: actions/checkout@v2
      with:
        repository: valet-testing/dast
        ref: ''
        path: _valet-testing_dast
        token: "${{ secrets.CHECKOUT_TOKEN }}"
#     # This item has no matching transformer
#     - environment: {}
#       taskId: a433f589-fce1-4460-9ee6-44a624aeb1fb
#       version: 1.*
#       name: Download Build Artifacts
#       refName: ''
#       enabled: true
#       alwaysRun: false
#       continueOnError: false
#       timeoutInMinutes: 0
#       retryCountOnTaskFailure: 0
#       definitionType: task
#       overrideInputs: {}
#       condition: succeeded()
#       inputs:
#         buildType: current
#         project: ''
#         definition: ''
#         specificBuildWithTriggering: 'false'
#         buildVersionToDownload: latest
#         allowPartiallySucceededBuilds: 'false'
#         branchName: refs/heads/master
#         buildId: ''
#         tags: ''
#         downloadType: single
#         artifactName: tesing
#         itemPattern: "**"
#         downloadPath: "${{ github.workspace }}"
#         parallelizationLimit: '8'
#         checkDownloadedFiles: 'false'
#         retryDownloadCount: '4'
#     # This item has no matching transformer
#     - environment: {}
#       taskId: 263abc27-4582-4174-8789-af599697778e
#       version: 0.*
#       name: Download GitHub Release
#       refName: ''
#       enabled: true
#       alwaysRun: false
#       continueOnError: false
#       timeoutInMinutes: 0
#       retryCountOnTaskFailure: 0
#       definitionType: task
#       overrideInputs: {}
#       condition: succeeded()
#       inputs:
#         connection: '085215ec-fd70-4f71-b014-08011768838e'
#         userRepository: slowslipper/build-playground
#         defaultVersionType: latest
#         version: ''
#         itemPattern: "**"
#         downloadPath: "${{ github.workspace }}"
    - name: Setup Java 16
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '16'
    - name: Ant ${{ env.TARGETS }} build.xml
      run: ant ${{ env.TARGETS }} -buildfile build.xml
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v1.7
      if: always()
      with:
        files: "**/TEST-*.xml"
    - name: dotnet build
      run: dotnet build unicorn
  Stage-1-job-2:
    needs:
    - Stage-1-job-1
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: true
    env:
      ALT: one1, one2
      TARGETS: suite1,suite2
      favorite_ice_cream: Mango
      favorite_movie: Pride and Prejudice
    if: # roll back deployment stage triggers are not supported
        github.event_type != 'pull_request'
    strategy:
    steps:
#     # This item has no matching transformer
#     - environment: {}
#       taskId: 537fdb7a-a601-4537-aa70-92645a2b5ce4
#       version: 1.*
#       name: 'Azure Function: test.com'
#       refName: ''
#       enabled: true
#       alwaysRun: false
#       continueOnError: false
#       timeoutInMinutes: 0
#       retryCountOnTaskFailure: 0
#       definitionType: task
#       overrideInputs: {}
#       condition: succeeded()
#       inputs:
#         function: test.com
#         key: '123455'
#         method: POST
#         headers: "{\n\"Content-Type\":\"application/json\", \n\"PlanUrl\": \"${{ env.system_CollectionUri }}\", \n\"ProjectId\": \"${{ env.system_TeamProjectId }}\", \n\"HubName\": \"build\", \n\"PlanId\": \"${{ env.system_PlanId }}\", \n\"JobId\": \"${{ github.job }}\", \n\"TimelineId\": \"${{ env.system_TimelineId }}\", \n\"TaskInstanceId\": \"${{ env.system_TaskInstanceId }}\", \n\"AuthToken\": \"${{ env.system_AccessToken }}\"\n}"
#         queryParameters: ''
#         body: ''
#         waitForCompletion: 'false'
#         successCriteria: ''
#     # This item has no matching transformer
#     - environment: {}
#       taskId: 28782b92-5e8e-4458-9751-a71cd1492bae
#       version: 1.*
#       name: Delay by 0 minutes
#       refName: ''
#       enabled: true
#       alwaysRun: false
#       continueOnError: false
#       timeoutInMinutes: 0
#       retryCountOnTaskFailure: 0
#       definitionType: task
#       overrideInputs: {}
#       condition: succeeded()
#       inputs:
#         delayForMinutes: '0'
  Stage-1-job-3:
    needs:
    - Stage-1-job-2
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: true
    env:
      ALT: one1, one2
      TARGETS: suite1,suite2
      favorite_ice_cream: Mango
      favorite_movie: Pride and Prejudice
    if: # roll back deployment stage triggers are not supported
        github.event_type != 'pull_request'
    timeout-minutes: 100
    steps:
    # If `begonaguereca/artifacts` is the same as the current repository, the `token` property can be removed.
    - uses: actions/checkout@v2
      with:
        repository: begonaguereca/artifacts
        ref: main
        fetch-depth: '1'
        path: _begonaguereca_artifacts
        submodules: 'true'
        token: "${{ secrets.CHECKOUT_TOKEN }}"
    - uses: Azure/login@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
    - uses: azure/CLI@v1
      with:
        inlineScript: az storage blob download --name storage_this --file test
    # If `build-playground/build-playground` is the same as the current repository, the `token` property can be removed.
    - uses: actions/checkout@v2
      with:
        repository: build-playground/build-playground
        path: _build-playground_tfvc
        token: "${{ secrets.CHECKOUT_TOKEN }}"
    - uses: dsaltares/fetch-gh-release-asset@0.06
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        repo: begonaguereca/American_Flag
        version: '1.2'
    - name: Authenticate GitHub Packages
      uses: whelk-io/maven-settings-xml-action@v20
      repositories: '[{"id":"1","url":"https://maven.pkg.github.com/${{ env.PACKAGES_OWNER }}/${{ env.PACKAGES_REPOSITORY }}"}]'
      servers: '[{"id":"1","username":"${{ env.PACKAGES_USERNAME }}","password":"${{ secrets.PACKAGES_TOKEN }}"}]'
    # # Ensure the following is included in your pom.xml file
    # <dependencies>
    #   <dependency>
    #     <groupId>1</groupId>
    #     <artifactId>1</artifactId>
    #     <version>latest</version>
    #   </dependency>
    # </dependencies>
    - name: Install Maven packages
      run: mvn install -s ~/.m2/settings.xml
    - name: Authenticate GitHub Packages
      run: echo '//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}' > ~/.npmrc
    - name: Install NPM packages
      run: npm install @${{ env.PACKAGES_OWNER }}/1@latest --registry=https://npm.pkg.github.com/${{ env.PACKAGES_OWNER }}
#     # GitHub Packages does not support downloading `python` packages
#     # GitHub Packages does not support downloading `universal` packages
    # If `valet-testing/dast` is the same as the current repository, the `token` property can be removed.
    - uses: actions/checkout@v2
      with:
        repository: valet-testing/dast
        ref: ''
        path: _valet-testing_dast
        token: "${{ secrets.CHECKOUT_TOKEN }}"
    - name: Setup Java 16
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '16'
    - name: Ant  build.xml
      run: ant -buildfile build.xml
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v1.7
      if: always()
      with:
        files: "**/TEST-*.xml"
  Unicorn-Stage:
    needs:
    - Stage-1-job-3
    runs-on: windows-latest
    concurrency:
#       # GitHub Actions does not support parallel deployments
    if: github.event_type != 'pull_request'
    strategy:
    steps:
    # If `begonaguereca/artifacts` is the same as the current repository, the `token` property can be removed.
    - uses: actions/checkout@v2
      with:
        repository: begonaguereca/artifacts
        ref: main
        fetch-depth: '1'
        path: _begonaguereca_artifacts
        submodules: 'true'
        token: "${{ secrets.CHECKOUT_TOKEN }}"
    - uses: Azure/login@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
    - uses: azure/CLI@v1
      with:
        inlineScript: az storage blob download --name storage_this --file test
    - uses: dsaltares/fetch-gh-release-asset@0.06
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        repo: begonaguereca/American_Flag
        version: '1.2'
    - name: kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: v1.7.0
    - name: kubectl
      shell: bash
      working-directory: "${{ github.workspace }}"
      run: kubectl  -o json
    - name: dotnet build
      run: dotnet build
