name: jenkout-wysiwyg
on:
  schedule:
  - cron: 15 13 * * *
  push:
    branches:
    - main
    - master
    - new_branch
  pull_request:
    branches:
    - master
    - other_branch
    - build_trigger_branch
env:
  1st-secret variable: "${PARAM-Expression-Field}"
  2nd-secret-variable: "${Secret}"
jobs:
  build:
    runs-on: jenkins-permanent-linux-agent
    steps:
    - name: run command
      run: |-
        true
        echo "executed shell script"
        echo "Addional code running for shell script"
#    - uses: hudson.plugins.copyartifact.CopyArtifact
#      with:
#        plugin: copyartifact@1.45
#        project: "/jenkout fake-repo/main"
#        filter: output/env.txt
#        target: 
#        excludes: 
#        selector:
#          class: hudson.plugins.copyartifact.StatusBuildSelector
#        doNotFingerprintArtifacts: 'false'
    needs: []
