name: begonaguereca/Python
on:
  push: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v2
    - name: run first python script
      continue-on-error: true
      run: |
        echo shell
        ls -al
        pwd
    - name: run second python script
      continue-on-error: true
      run: |
        echo shell
        ls -al
        pwd
    - name: run third python script
      continue-on-error: true
      run: |
        python -c "import sys; print(sys.version)"
        
