name: health cheaks
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with: 
        args: |-
          -Dsonar.projectKey='begonaguereca_jenkins'/`
          -Dsonar.organization='begonaguereca'/`
          -Dsonar.host.url='${{ secrets.SONAR_URL }}'/`
          -Dsonar.login=${{ env.SONAR_TOKEN }}
