on:
  push:
    branches:
    - master
name: Push Event
env: 
  BOO: "push"
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: echo "hello world"
      if: "env.FOO == github.event_name"
      
    
