name: CI

on: [push, pull_request_target]

env:
#   # This item is not mapped to a GitHub Actions equivalent
#   PYTHONPATH: '"${env.WORKSPACE}/cworg"'
  DJANGO_SETTINGS_MODULE: DjangoApp.settings
#   # This item is not mapped to a GitHub Actions equivalent
#   BUILD_NUMBER: '"${env.BUILD_NUMBER}"'
jobs:
  Initialize:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
#     # This item is not mapped to a GitHub Actions equivalent
#     - script:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: |-
#             echo "${BUILD_NUMBER} - ${env.BUILD_ID} on ${env.JENKINS_URL}"
#                                 echo "Branch Specifier :: ${params.SPECIFIER}"
  Checkout:
    runs-on: ubuntu-latest
    needs: Initialize
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: checkout
      uses: actions/checkout@v2
      with:
        repository: begonaguereca/demo_repo_name
  Make-Virtual-Env:
    name: Make Virtual Env
    runs-on: ubuntu-latest
    needs: Checkout
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: Python3
    - name: sh
      shell: bash
      run: python -m pip install pytest
    - name: sh
      shell: bash
      run: python -m pip install allure-pytest
    - name: sh
      shell: bash
      run: python -m pytest -v test_allure.py --alluredir=allure-results
  Bootstrap:
    runs-on: ubuntu-latest
    needs: Make-Virtual-Env
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: Python3
    - name: sh
      shell: bash
      run: make bootstrap
      working-directory: cworg
  Build:
    runs-on: ubuntu-latest
    needs: Bootstrap
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: Python3
    - name: sh
      shell: bash
      run: make static
      working-directory: cworg
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: Python3
    - name: sh
      shell: bash
      run: python3 -m pytest
      working-directory: "./"
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: sh
      shell: bash
      run: ssh webapp@my-server.com'~/deploy-my-django-app.sh'

