name: valet-project/If-Condition-variables-update
on: [push, pull_request]
concurrency: 
  group: ${{ github.base_ref }}
  cancel-in-progress: true
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install CMake (Windows)
      run: echo ${{ github.base_ref }}

