
on:
  push:
    branches:
    - master
name: Push Event
env: 
  BOO: 'ah'
  UNICORN: 'real'
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: echo "hello world"
      if: "${{ env.BOO == 'ah' }}" 

