name: jenkout-testing/12
on:
  push:
  pull_request:

env:
  CF_APP: reponame

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo ${{ join(fromJson('["foo", "-", "bar"]')) }}
    - run: echo "winning"
      if: ${{ join(fromJson('["foo", "-", "bar"]')) == 'foo-bar' }}

