name: CI

on: [push, pull_request_target]


jobs:
  Initialize:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
  Checkout:
    runs-on: ubuntu-latest
    needs: Initialize
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
  Make-Virtual-Env:
    name: Make Virtual Env
    runs-on: ubuntu-latest
    needs: Checkout
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: sh
      shell: bash
      run: python -m pip install pytest
    - name: sh
      shell: bash
      run: python -m pip install allure-pytest
    - name: sh
      shell: bash
      run: python -m pytest -v test_allure.py --alluredir=allure-results
