name: xcode
on:
  push:
  workflow_dispatch:
    inputs:
      example-parameter:
        required: false
        default: latest
      example-parameter-two:
        required: false
        default: "~/main"
jobs:
  build:
    steps:
    - name: checkout
      uses: actions/checkout@v
