name: health cheaks
on:
  push:
jobs:
  test_2:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.0
    - run: gem install bundler
    - run: bundle install --jobs=3 --retry=3
    - run: echo "child"


