name: xcode
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elasticsearch:6.5.0
    steps:
    - name: checkout
      uses: actions/checkout@v2
