name: jenkout-testing/12
on:
  push:
  pull_request:

env:
  FOO: FOO_CHILD
  FOO_CHILD: real_property

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo "$(date +'%Y-%m-%d')"
    - run: echo $(date +'%Y-%m-%dT%H:%M:%S')
    - run: echo ${TIMESTAMP}
