name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - if: "${{ job.status == 'success' }}"
      uses: ouzi-dev/commit-status-updater@v1.1.0
      with:
        status: "error"
        url: http://myurl.io/
        description: "Sucess is not good enough"
        name: "name of my status check"
