name: Push Event
on:
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.rvm }}"
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
    strategy:
      matrix:
        ISOLATED:
        - true
        - false
        rvm:
        - 2.5
        - 2.2
        os:
        - ubuntu-latest
        - windows-latest
    env:
      ISOLATED: "${{ matrix.ISOLATED }}"
  test_2:
    runs-on: ubuntu-latest
    if: ${{ true }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_3:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_4:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master' }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_5:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ env.foo }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ env.foo }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ env.foo }}"
    - run: echo 'parent before_script'
      if: "${{ env.foo }}"
    - run: echo 'parent script'
      if: "${{ env.foo }}"
  test_6:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ !env.foo }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ !env.foo }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ !env.foo }}"
    - run: echo 'parent before_script'
      if: "${{ !env.foo }}"
    - run: echo 'parent script'
      if: "${{ !env.foo }}"
  test_7:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ !env.foo }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ !env.foo }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ !env.foo }}"
    - run: echo 'parent before_script'
      if: "${{ !env.foo }}"
    - run: echo 'parent script'
      if: "${{ !env.foo }}"
  test_8:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ !env.foo }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ !env.foo }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ !env.foo }}"
    - run: echo 'parent before_script'
      if: "${{ !env.foo }}"
    - run: echo 'parent script'
      if: "${{ !env.foo }}"
  test_9:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ env.foo }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ env.foo }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ env.foo }}"
    - run: echo 'parent before_script'
      if: "${{ env.foo }}"
    - run: echo 'parent script'
      if: "${{ env.foo }}"
  test_10:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ !!env.foo }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ !!env.foo }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ !!env.foo }}"
    - run: echo 'parent before_script'
      if: "${{ !!env.foo }}"
    - run: echo 'parent script'
      if: "${{ !!env.foo }}"
  test_11:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ env.foo }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ env.foo }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ env.foo }}"
    - run: echo 'parent before_script'
      if: "${{ env.foo }}"
    - run: echo 'parent script'
      if: "${{ env.foo }}"
  test_12:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ !env.foo }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ !env.foo }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ !env.foo }}"
    - run: echo 'parent before_script'
      if: "${{ !env.foo }}"
    - run: echo 'parent script'
      if: "${{ !env.foo }}"
  test_13:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ !env.foo }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ !env.foo }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ !env.foo }}"
    - run: echo 'parent before_script'
      if: "${{ !env.foo }}"
    - run: echo 'parent script'
      if: "${{ !env.foo }}"
  test_14:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ !env.foo }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ !env.foo }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ !env.foo }}"
    - run: echo 'parent before_script'
      if: "${{ !env.foo }}"
    - run: echo 'parent script'
      if: "${{ !env.foo }}"
  test_15:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ env.foo }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ env.foo }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ env.foo }}"
    - run: echo 'parent before_script'
      if: "${{ env.foo }}"
    - run: echo 'parent script'
      if: "${{ env.foo }}"
  test_16:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ !!env.foo }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ !!env.foo }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ !!env.foo }}"
    - run: echo 'parent before_script'
      if: "${{ !!env.foo }}"
    - run: echo 'parent script'
      if: "${{ !!env.foo }}"
  test_17:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ env.FOO == github.event_name }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ env.FOO == github.event_name }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ env.FOO == github.event_name }}"
    - run: echo 'parent before_script'
      if: "${{ env.FOO == github.event_name }}"
    - run: echo 'parent script'
      if: "${{ env.FOO == github.event_name }}"
  test_18:
    runs-on: ubuntu-latest
    if: ${{ join(fromJson('["env.ONE", "env.OTHER"]')) == 'foo-bar' }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_19:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ env.FOO == env.BAR }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ env.FOO == env.BAR }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ env.FOO == env.BAR }}"
    - run: echo 'parent before_script'
      if: "${{ env.FOO == env.BAR }}"
    - run: echo 'parent script'
      if: "${{ env.FOO == env.BAR }}"
  test_20:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_21:
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson('["one", "other"]'), github.ref) }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_22:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: ${{ contains(fromJson('["env.ONE", "env.OTHER"]'), github.repository) }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: ${{ contains(fromJson('["env.ONE", "env.OTHER"]'), github.repository) }}
    - run: bundle install --jobs=3 --retry=3
      if: ${{ contains(fromJson('["env.ONE", "env.OTHER"]'), github.repository) }}
    - run: echo 'parent before_script'
      if: ${{ contains(fromJson('["env.ONE", "env.OTHER"]'), github.repository) }}
    - run: echo 'parent script'
      if: ${{ contains(fromJson('["env.ONE", "env.OTHER"]'), github.repository) }}
  test_23:
    runs-on: ubuntu-latest
    if: ""
    steps:
    - name: checkout
      uses: actions/checkout@v2
      if: "${{ env.env.FOO }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
      if: "${{ env.env.FOO }}"
    - run: bundle install --jobs=3 --retry=3
      if: "${{ env.env.FOO }}"
    - run: echo 'parent before_script'
      if: "${{ env.env.FOO }}"
    - run: echo 'parent script'
      if: "${{ env.env.FOO }}"
  test_24:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'schedule' }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_25:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.ref == 'refs/tags/bar' }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_26:
    runs-on: ubuntu-latest
    if: ${{ !github.ref == 'refs/heads/master' }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_27:
    runs-on: ubuntu-latest
    if: ${{ !github.ref == 'refs/heads/master' && github.event_name == 'schedule' || github.ref == 'refs/tags/bar' }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_28:
    runs-on: ubuntu-latest
    if: ${{ (github.ref == 'refs/tags/release') && (github.ref == 'refs/heads/master') }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  build:
    needs:
    - test
    - test_2
    - test_3
    - test_4
    - test_5
    - test_6
    - test_7
    - test_8
    - test_9
    - test_10
    - test_11
    - test_12
    - test_13
    - test_14
    - test_15
    - test_16
    - test_17
    - test_18
    - test_19
    - test_20
    - test_21
    - test_22
    - test_23
    - test_24
    - test_25
    - test_26
    - test_27
    - test_28
    runs-on: ubuntu-latest
    env:
      ISOLATED: true
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo "child build"
  deploy:
    needs:
    - test
    - test_2
    - test_3
    - test_4
    - test_5
    - test_6
    - test_7
    - test_8
    - test_9
    - test_10
    - test_11
    - test_12
    - test_13
    - test_14
    - test_15
    - test_16
    - test_17
    - test_18
    - test_19
    - test_20
    - test_21
    - test_22
    - test_23
    - test_24
    - test_25
    - test_26
    - test_27
    - test_28
    - build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo "child deploy"
#     # deploy transformations are currently not supported
