name: xcode
on:
  workflow_dispatch:
    inputs:
      example-parameter:
        required: false
        default: latest
      example-parameter-two:
        required: false
        default: "~/main"
jobs:
  build:
    runs-on:
      - macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        cache: npm
