name: jenkout-testing/12
on:
  push:
  pull_request:

env:
  FOO: FOO_CHILD
  FOO_CHILD: real_property

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo ${{ steps.date.outputs.date }}
    - run: echo "${{ steps.date.outputs.date }}"
    - run: echo ${TIMESTAMP}
