name: valet-dev-testing/travis-github-pages
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: main
        folder: "./path"
        token: "${{ secrets.GITHUB_TOKEN }}"
        commit_message: Deploying a GitHub page
        git_config_name: savy_dev
        git_config_email: savy_dev@github.com
