name: jenkout-testing/travis-mega-pipeline
on:
  push:
    branches:
    - master
    - stable
env:
  CAMPFIRE_TOKEN: abc123
  TIMEOUT: '1000'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        USE_NETWORK:
        - 'true'
        - 'false'
        ISOLATED:
        - true
        - false
        node_js:
        - 2.5
        - 2.2
        os:
        - ubuntu-latest
        - windows-latest
        include:
        - FOO: bar
          BAR: foo
        exclude:
        - node_js: 2.2
          os: linux
    steps:
    - name: checkout
      uses: actions/checkout@v2
#     # 'os' dependencies are currently unsupported
    - uses: actions/setup-node@v2
      with:
        node-version: "${{ matrix.node_js }}"
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
    env:
      FOO: "${{ matrix.FOO }}"
      BAR: "${{ matrix.BAR }}"
      USE_NETWORK: "${{ matrix.USE_NETWORK }}"
      ISOLATED: "${{ matrix.ISOLATED }}"
  test_2:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: echo 'before install is working'
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_3:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: echo 'install is working'
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_4:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'before script is working'
    - run: echo 'parent script'
  test_5:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'script is working'
  test_6:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
    - run: echo 'after_script is working'
  test_7:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo 'before cache is working'
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_8:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
    - run: echo 'after failure is working'
  test_9:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
    - run: echo 'after success is working'
  test_10:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
    - run: echo 'before deploy is working'
  test_11:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
    - run: echo 'after deploy is working'
  test_12:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [true]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_13:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [branch = master]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_14:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [branch != master]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_15:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [env(foo) IS present]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_16:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [env(foo) IS NOT present]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_17:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [NOT env(foo) IS present]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_18:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [env(foo) IS blank]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_19:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [env(foo) IS NOT blank]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_20:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [NOT env(foo) IS blank]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_21:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [env(foo) IS true]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_22:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [env(foo) IS NOT true]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_23:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [NOT env(foo) IS true]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_24:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [env(foo) IS false]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_25:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [env(foo) IS NOT false]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_26:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [NOT env(foo) IS false]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_27:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [env(FOO) = type]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_28:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [concat("foo", "-", "bar") = "foo-bar"]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_29:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [env(FOO) = env(BAR)]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_30:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [branch =~ /^(one|two)-three$/]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_31:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [branch IN (one, other)]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_32:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [repo IN (env(ONE), env(OTHER))]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_33:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [env(env(FOO))]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_34:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [branch = master AND type = cron]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_35:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [type = cron OR tag = bar]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_36:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [NOT branch = master]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_37:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [NOT branch = master AND type = cron OR tag = bar]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  test_38:
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [((tag = release) AND (branch = master))]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo 'parent script'
  build:
    needs:
    - test
    - test_2
    - test_3
    - test_4
    - test_5
    - test_6
    - test_7
    - test_8
    - test_9
    - test_10
    - test_11
    - test_12
    - test_13
    - test_14
    - test_15
    - test_16
    - test_17
    - test_18
    - test_19
    - test_20
    - test_21
    - test_22
    - test_23
    - test_24
    - test_25
    - test_26
    - test_27
    - test_28
    - test_29
    - test_30
    - test_31
    - test_32
    - test_33
    - test_34
    - test_35
    - test_36
    - test_37
    - test_38
    runs-on: ubuntu-latest
    env:
      ISOLATED: true
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo "child build"
  deploy:
    needs:
    - test
    - test_2
    - test_3
    - test_4
    - test_5
    - test_6
    - test_7
    - test_8
    - test_9
    - test_10
    - test_11
    - test_12
    - test_13
    - test_14
    - test_15
    - test_16
    - test_17
    - test_18
    - test_19
    - test_20
    - test_21
    - test_22
    - test_23
    - test_24
    - test_25
    - test_26
    - test_27
    - test_28
    - test_29
    - test_30
    - test_31
    - test_32
    - test_33
    - test_34
    - test_35
    - test_36
    - test_37
    - test_38
    - build
    runs-on: ubuntu-latest
    if: ${{ success() }}
#       # 'if' transformations are currently unsupported: [branch = master]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 2.5
    - run: npm install
    - run: echo 'parent before_script'
    - run: echo "child deploy"
#     # deploy transformations are currently not supported
