name: valet-dev-testing/postgres
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: apt-get -y install postgresql-11 postgresql-client-11
    - run: bundle install --jobs=3 --retry=3
    - run: rake
    services:
      postgresql:
        image: postgres:11
