name: valet-dev-testing/travis-github-pages
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  build:
    container:
      image: "circleci/node:9.6.1"
      credentials:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
