name: jenkout-testing/15
on:
  workflow_dispatch:
env:
  DOCKER_TAG: "`git rev-parse --short HEAD`x"
  IKS_BETA_VERSION: '1'
  SONAR_TOKEN: "$SONAR_TOKEN"
  SONAR_NOTIFY_HOOK: "$SLACK_WEBHOOK"
  SLACK_SECURITY_HOOK: "$SLACK_SECURITY_WEBHOOK"
  ACCOUNT: "$ACCOUNT"
  CLOUD_API_KEY: "$CLOUD_API_KEY"
jobs:
  Lint & Audit & Publish:
    runs-on: ubuntu 18.04
    env:
      TASK: lint
    steps:
    - name: checkout
      uses: actions/checkout@v2
#     # cache transformations are currently not supported
    - run: curl -sL https://ibm.biz/idt-installer | bash
    - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - run: some-cloud plugin update container-service
    - run: npm ci --ignore-scripts
    - run: npm run lint
#     # notifications transformations are currently not supported
#       - env: TASK=CR_cleanup
  Lint & Audit & Publish_2:
    runs-on: ubuntu 18.04
    env:
      TASK: audit
    steps:
    - name: checkout
      uses: actions/checkout@v2
#     # cache transformations are currently not supported
    - run: curl -sL https://ibm.biz/idt-installer | bash
    - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - run: some-cloud plugin update container-service
    - run: npm ci --ignore-scripts
    - run: npm run audit
#     # notifications transformations are currently not supported
    services:
#       # 'services' transformations are currently unsupported
#       - docker
    continue-on-error:
#       # 'continue-on-error' transformations are currently unsupported
#       allow_failures:
#       - env: TASK=CR_cleanup
  Lint & Audit & Publish_3:
    runs-on: ubuntu 18.04
    env:
      TASK: CR_cleanup
    steps:
    - name: checkout
      uses: actions/checkout@v2
#     # cache transformations are currently not supported
    - run: curl -sL https://ibm.biz/idt-installer | bash
    - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - run: some-cloud plugin update container-service
    - run: npm ci --ignore-scripts
    - run: "./bin/some-cloud.login.sh"
    - run: "./bin/some-cloud.cr.cleanup.sh"
#     # notifications transformations are currently not supported
    services:
#       # 'services' transformations are currently unsupported
#       - docker
    continue-on-error:
#       # 'continue-on-error' transformations are currently unsupported
#       allow_failures:
#       - env: TASK=CR_cleanup
  Lint & Audit & Publish_4:
    runs-on: ubuntu 18.04
    env:
      TASK: publish
    steps:
    - name: checkout
      uses: actions/checkout@v2
#     # cache transformations are currently not supported
    - run: curl -sL https://ibm.biz/idt-installer | bash
    - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - run: some-cloud plugin update container-service
    - run: npm ci --ignore-scripts
    - run: "./bin/some-cloud.login.sh"
    - run: npm run docker:prodpublish
#     # notifications transformations are currently not supported
    services:
#       # 'services' transformations are currently unsupported
#       - docker
    continue-on-error:
#       # 'continue-on-error' transformations are currently unsupported
#       allow_failures:
#       - env: TASK=CR_cleanup
  Vulnerability Assessment:
    needs:
    - Lint & Audit & Publish
    - Lint & Audit & Publish_2
    - Lint & Audit & Publish_3
    - Lint & Audit & Publish_4
    runs-on: ubuntu 18.04
    env:
      TASK: Vulnerability_Analysis
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
#     # cache transformations are currently not supported
    - run: curl -sL https://ibm.biz/idt-installer | bash
    - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - run: some-cloud plugin update container-service
    - run: npm ci --ignore-scripts
    - run: "./bin/vulnerability-scanner.sh ${DOCKER_TAG}"
#     # notifications transformations are currently not supported
    services:
#       # 'services' transformations are currently unsupported
#       - docker
    continue-on-error:
#       # 'continue-on-error' transformations are currently unsupported
#       allow_failures:
#       - env: TASK=CR_cleanup
  Deploy:
    needs:
    - Lint & Audit & Publish
    - Lint & Audit & Publish_2
    - Lint & Audit & Publish_3
    - Lint & Audit & Publish_4
    - Vulnerability Assessment
    runs-on: ubuntu 18.04
    env:
      TASK: deploy-staging
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
#     # cache transformations are currently not supported
    - run: curl -sL https://ibm.biz/idt-installer | bash
    - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - run: some-cloud plugin update container-service
    - run: npm ci --ignore-scripts
    - run: "./bin/some-cloud.login.sh"
    - run: "./bin/update.k8s.staging.sh"
#     # notifications transformations are currently not supported
    services:
#       # 'services' transformations are currently unsupported
#       - docker
    continue-on-error:
#       # 'continue-on-error' transformations are currently unsupported
#       allow_failures:
#       - env: TASK=CR_cleanup
  Sonar:
    needs:
    - Lint & Audit & Publish
    - Lint & Audit & Publish_2
    - Lint & Audit & Publish_3
    - Lint & Audit & Publish_4
    - Vulnerability Assessment
    - Deploy
    runs-on: ubuntu 18.04
    env:
      TASK: sonar
    steps:
    - name: checkout
      uses: actions/checkout@v2
#     # cache transformations are currently not supported
    - run: curl -sL https://ibm.biz/idt-installer | bash
    - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - run: some-cloud plugin update container-service
    - run: npm ci --ignore-scripts
    - run: "./bin/sonar.sh"
    - run: "./bin/some-cloud.login.sh"
    - run: |
        docker run \
          -e SONAR_TOKEN=${SONAR_TOKEN} \
          -e SONAR_NOTIFY_HOOK=${SONAR_NOTIFY_HOOK} \
          -e PROJECT_TOKEN=cs360 \
          us.icr.io/sonar-slack-reporter/sonar-slack-reporter:latest
#     # notifications transformations are currently not supported
    services:
#       # 'services' transformations are currently unsupported
#       - docker
    continue-on-error:
#       # 'continue-on-error' transformations are currently unsupported
#       allow_failures:
#       - env: TASK=CR_cleanup
