name: GitHub Actions Demo
on: [push]
concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
