name: valet-dev-testing/travis-github-pages
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run command
      shell: bash
      run: |-
        mvn cargo:undeploy
        mvn clean
        mvn install
        mvn cargo:deploy
      if: always()
