name: valet-project/If-Condition-variables-update
on:
  push:
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install CMake (Windows)
      run: echo ${{ github.head_ref }}

