name: valet-dev-testing/travis-github-pages
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: main
        folder: "."
        repository-name: Valet
        token: "${{ secrets.GITHUB_TOKEN }}"
        commit-message: Deploying a GitHub page
        git-config-name: "${{ github.event.repository.name }}"
        git-config-email: savy_dev@github.com
    - run: echo 'deploying the second version'
