name: Node.js 
on:
  push
jobs:
  build:
    runs-on: # this agent type is not supported: [trusty]
      ubuntu-latest
    if: # "artifact triggers are not supported"
        github.event_type != 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.workflow }}
      - run: echo ${{ job.name }}
      - run: echo ${{ job.id }}
      - run: echo "#{ job.name }"

