name: Push Event
on:
  push:
    branches:
    - master
jobs:
  test_2:
    services:
      couchdb:
        image: couchdb
    
    runs-on: ubuntu-latest
    env: 
      foo: "bar"
    steps:
    - name: checkout
      uses: actions/checkout@v2
