name: begonaguereca/Python
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run python script
      shell: python
      run: |-
        collection = ['hey', 5, 'd']
        for x in collection:
            print(x)
      continue-on-error: true
    - name: run python script
      shell: bash
      run: python my_script.py
      continue-on-error: true
    - name: run python script
      shell: bash
      run: |-
        echo shell
        ls -al
        pwd
    # - Unsupported parameter 'XShell is not supported in Github Actions. Please ensure that the correct shell type is configured' with value 'xshell'
    - name: run python script
      shell: bash
      run: |-
        echo shell
        ls -al
        pwd

