name: xcode
on:
  push
jobs:
  build:
    runs-on:
      - macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install the Apple certificate and provisioning profile
      env:
        BUILD_CERTIFICATE_BASE64: "${{ secrets.BUILD_CERTIFICATE_BASE64 }}"
        P12_PASSWORD: "${{ secrets.P12_PASSWORD }}"
        BUILD_PROVISION_PROFILE_BASE64: "${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}"
        KEYCHAIN_PASSWORD: "${{ secrets.KEYCHAIN_PASSWORD }}"
      run: |
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
