name: jenkout-testing/12
on:
  push:

env:
  CF_APP: reponame

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo "boo"
      if: ${{ github.event_name == pull request }}
