name: Node.js 
on:
  push
jobs:
  build:
    if: # "artifact triggers are not supported"
        failure() && github.event_type == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.workflow }}
      - run: echo ${{ job.name }}
      - run: echo ${{ job.id }}
      - run: echo "#{ job.name }"

