name: CI

on: [push, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: run python script
      shell: python
      run: |-
        pip install tox
         sh this_is_it
      continue-on-error: true

