name: health cheaks
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
      run: |-
        sonar-scanner/`
        /k:'begonaguereca_jenkins'/`
        /d:sonar.organization='begonaguereca'/`
        /d:sonar.host.url='${{ secrets.SONAR_URL }}'/`
        /d:sonar.login=${{ env.SONAR_TOKEN }}
