name: begonaguereca/virtual-env-python
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: python3
    - name: sh
      shell: bash
      run: python setup.py install
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: python3
    - name: run python script
      shell: bash
      run: python setup.py install
      continue-on-error: true
