name: begonaguereca/Python
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
#     # This item is not mapped to a GitHub Actions equivalent
#     - uses: jenkins.plugins.shiningpanda.builders.PythonBuilder
#       with:
#         plugin: shiningpanda@0.24
#         pythonName: '2.6'
#         nature: python
#         command: "print(\"regular python builder\")\n\nimport sys; \n\nprint(sys.version)"
#         ignoreExitCode: 'false'
    - name: set up python
      uses: actions/setup-python@v2
    - name: run python script
      shell: python
      run: |-
        print("regular python builder")
        import sys
        print(sys.version)
      continue-on-error: true
    - name: set up python
      uses: actions/setup-python@v2
    - name: run python script
      shell: python
      run: |-
        print("Virtual env- no clear")
        print(sys.version)
      continue-on-error: true
    - name: set up python
      uses: actions/setup-python@v2
    - name: run python script
      shell: python
      run: |-
        print("Virtual env- clear")
        print(sys.version)
      continue-on-error: true


