on:
  push:
    branches:
    - master
env: 
 foo: "test"
jobs:
  test_5:
    runs-on: ubuntu-latest
    if: ${{ env.foo }}"
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - run: bundle install --jobs=3 --retry=3
    - run: echo 'parent before_script'
    - run: echo 'parent script'
