name: begonaguereca/Python
on:
  push: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v2
    - name: run python script
      run: |
        echo shell
        ls -al
        pwd
        
