name: health cheaks
on:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        workflow: "${{ env.WORKFLOW_NAME }}"
        workflow_conclusion: "${{ env.CONCLUSION }}"
        name: "${{ env.ARTIFACT_NAME }}"
        path: "${{ env.TARGET_PATH }}"
        repo: "${{ env.REPO }}"
      env:
        WORKFLOW_NAME: UPDATE_ME
        CONCLUSION: completed,success
        TARGET_PATH: moved
        ARTIFACT_NAME: UPDATE_ME
        REPO: "${{github.repository}}"
      continue-on-error: false
