name: Push Event
on:
  push:
    branches:
    - master
jobs:
  test_2:
    services:
      postgresql:
        image: postgres
      mongodb:
        image: mongo
      cassandra:
        image: cassandra
    
    runs-on: ubuntu-latest
    env: 
      foo: "bar"
    steps:
    - name: checkout
      uses: actions/checkout@v2
