name: valet-dev-testing/travis-github-pages
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  build:
    container:
      image: circleci/ruby:2.5.1-node-browsers
      credentials:
        username: mydockerhub-user
        password: "$DOCKERHUB_PASSWORD"
      env:
        FOO: BAR
      options: "--entrypoint entrypoint.sh --name my_docker_name --user my_username --smallfiles"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
