name: xcode
on:
  push
jobs:
  build:
    runs-on:
      - macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        cache: npm
