name: valet-dev-testing/travis-github-pages
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan -H 192.168.1.162 >> ~/.ssh/known_hosts
      - uses: actions/checkout@v1
    
