name: Push Event
on:
  push:
    branches:
    - master
env: 
  BOO: 'ahhh'
  UNICORN: 'real'
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: echo "hello world"
      if: "${{ env.BOO == 'ahhh' }}" 

