name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clean workspace
      shell: bash
      run: |-
        #!/usr/bin/env ruby
        require "fileutils"
        Dir.chdir(ENV["GITHUB_WORKSPACE"]) do
          paths = Dir.glob(["include/pattern"])
          paths -= Dir.glob(["exclude/pattern/"])
          paths.each do |path|
            File.delete(path) if File.file?(path)
            FileUtils.rm_rf(path) if File.directory?(path) # if deleteDirs == true
          end
        end
      continue-on-error: true
      if: always()
