name: jenkout-testing/12
on:
  push:
  pull_request:

env:
  FOO: pew
  VAR: PEWWW

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo ${{ join(fromJson('[env.foo, env.var]'), '') }}
    - run: echo "winning"
      if: ${{ join(fromJson('["foo", "-", "bar"]'), '') == 'foo-bar' }}

