name: valet-project/If-Condition-variables-update
on:
  push:
    branches:
    - main
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install CMake (Windows)
      if: success() && env.Agent.OS == 'Windows_NT'
      run: echo hello
    - name: Enable test runs if configuration is valid
      if: success() && env.DoTestSteps == 'true'
      continue-on-error: true
      run: echo hello
