name: health cheaks
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - uses: manishsat/ado-download-artifact@v1
      with:
        buildDefinitionId: '63'
        artifactName: _build-playground
        projectId: 97d2995f-4fe1-4175-9c24-effd87124bba
        pattoken: "${{ secrets.AZURE_DEVOPS__BUILD-PLAYGROUND_TOKEN }}"
        orgName: "${{ secrets.AZURE_DEVOPS__BUILD-PLAYGROUND_ORG_NAME }}"
