name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clean workspace
      shell: ruby {0}
      run: |-
        require "fileutils"
        Dir.chdir(ENV["GITHUB_WORKSPACE"]) do
          paths = Dir.glob(["**/*.rb"])
          paths -= Dir.glob(["**/*.ts"])
          paths.each do |path|
            File.delete(path) if File.file?(path)
            FileUtils.rm_rf(path) if File.directory?(path)
          end
        end
