name: valet-dev-testing/travis-sonar
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: sonar scan
      uses: sonarsource/sonarcloud-github-action@v1.4
      env:
        SONAR_TOKEN: "${{ secrets.SONAR_STRING_TOKEN }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - run: rake
