name: valet-dev-testing/travis-github-pages
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Cucumber
      uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: "${{ secrets.GITHUB_TOKEN }}"
        path: "**/cucumber-report.json"
