name: valet-dev-testing/travis-heroku
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   config_validation: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: |-
        cat > ~/.netrc <<EOF
                          machine api.heroku.com
                            login $HEROKU_EMAIL
                            password $HEROKU_API_KEY
                          machine git.heroku.com
                            login $HEROKU_EMAIL
                            password $HEROKU_API_KEY
                        EOF
      env:
        HEROKU_API_KEY: "${{ secrets.HEROKU_API_KEY }}"
        HEROKU_EMAIL: "${{ secrets.HEROKU_EMAIL }}"
    - run: heroku git:remote --app ${{ github.event.repository.name }}
    - run: git push heroku main
    - run: heroku echo 'hello'
      if: "${{ success() }}"
